/* Lógico_1: */

CREATE TABLE ferramenta (
    TIPO_FERRAMENTA CHAR,
    COD_FERRAMENTA NUMERIC,
    ID_FERRAMENTA CHAR PRIMARY KEY,
    DESCRICAO CHAR,
    fk_CARRINHO_ID_CARRINHO CHAR
);

CREATE TABLE CARRINHO (
    COD_FERRAMENTA CHAR,
    ID_CARRINHO CHAR PRIMARY KEY,
    ID_FERRAMENTA CHAR,
    FK_FUNCIONARIO_ID_FUNCIONARIO CHAR
);

CREATE TABLE FUNCIONARIO (
    ID_CARRINHO CHAR,
    ID_FUNCIONARIO CHAR PRIMARY KEY
);
 
ALTER TABLE ferramenta ADD CONSTRAINT FK_ferramenta_2
    FOREIGN KEY (fk_CARRINHO_ID_CARRINHO)
    REFERENCES CARRINHO (ID_CARRINHO)
    ON DELETE CASCADE;
 
ALTER TABLE CARRINHO ADD CONSTRAINT FK_CARRINHO_2
    FOREIGN KEY (FK_FUNCIONARIO_ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
    ON DELETE CASCADE;